/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kependudukan.ui;

import com.kependudukan.entity.Users;
import com.kependudukan.util.KependudukanHibernateUtil;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 *
 * @author Rahmat Subandi
 */
public class frmUsers extends javax.swing.JFrame {

    private boolean tambahin = false;

    /**
     * Creates new form frmUsers
     */
    public frmUsers() {
        initComponents();
        
        setTitle("Halaman Input Data Kependudukan"); //title di GUI

        // Ketika dirun tampilan akan selalu ditengah layar PC
        // mengambil ukuran layar
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableKependudukan = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tableKependudukan.setAutoCreateRowSorter(true);
        tableKependudukan.setBackground(new java.awt.Color(255, 204, 204));
        tableKependudukan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tableKependudukan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKependudukanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableKependudukan);
        if (tableKependudukan.getColumnModel().getColumnCount() > 0) {
            tableKependudukan.getColumnModel().getColumn(0).setMaxWidth(50);
            tableKependudukan.getColumnModel().getColumn(1).setMinWidth(200);
            tableKependudukan.getColumnModel().getColumn(2).setMinWidth(150);
            tableKependudukan.getColumnModel().getColumn(3).setMinWidth(150);
            tableKependudukan.getColumnModel().getColumn(4).setMinWidth(150);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel1.setText("ID");

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        jLabel4.setText("Email");

        jLabel5.setText("Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassword)
                    .addComponent(txtEmail)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNama)
                    .addComponent(txtAlamat))
                .addGap(180, 180, 180))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnTambah.setBackground(new java.awt.Color(0, 0, 255));
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(0, 204, 255));
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(204, 0, 0));
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(255, 255, 0));
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(51, 204, 0));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(153, 153, 153));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUbah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBatal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel6.setText("Pencarian Menggunakan Id : ");

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txtCari)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Membuat query untuk form users
        query("from Users", false);
    }//GEN-LAST:event_formWindowActivated

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // Tombol Tambah
        tambahin = true; // jika fungsi tambahin benar
        cekFungsi(true); // Dan juga cek metod cekFungsi
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // Tombol Ubah
        tambahin = false; // jika fungsi tambahin salah
        cekFungsi(true); // Dan juga cek metod cekFungsi
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // Tombol Hapus
        // Menampilkan option pilihan
        int hapus = JOptionPane.showConfirmDialog(this, "Ingin menghapus data ini ?", "Kependudukan App", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        // Jika tombol ok di klik maka menghapus data dan memunculkan notifikasi
        if (hapus == JOptionPane.YES_OPTION) {
            query("DELETE FROM Users Where id = " + Integer.parseInt(txtID.getText()), true);
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!", "Kependudukan App", JOptionPane.OK_OPTION);
        } else { // Jika tidak maka akan batal menghapus data dan memunculkan notifikasi
            JOptionPane.showMessageDialog(this, "Data gagal dihapus!\nSilahkan coba lagi", "Kependudukan App", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // Tombol Batal
        cekFungsi(false);
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        /**
         * Fungsi dubawah ini untuk memasukan data ke database
         * yang mana berdasarkan id textfield contoh :
         * di inputan nama menggunakan txtNama lalu menggunakan perintah teks
         * atau getText
         */
        String sqlAdd = "INSERT INTO Users (nama, alamat, email, password) values('"
                + txtNama.getText() + "', '"
                + txtAlamat.getText() + "', '"
                + txtEmail.getText() + "', '"
                + txtPassword.getText() + "')";
        /**
         * Fungsi dibawah ini untuk mengupdate data di database
         * yang mana jika di Jframe table data yang di klik
         * lalu klin tombol ubah
         * maka dia akan mengupdat data tersebut dengan cara :
         * perintah sql 'UPDATE nama table yang ada di database'
         * lalu s sebagai parameternya
         * s.nama mengambil data nama di database yang akan di edit
         * Where s.id artinya berdasarka id
         */
        String sqlEdit = "UPDATE Users s SET "
                + "s.nama = '" + txtNama.getText()
                + "', s.alamat = '" + txtAlamat.getText()
                + "', s.email = '" + txtEmail.getText()
                + "', s.password = '" + txtPassword.getText() + "' "
                + "Where s.id = " + txtID.getText();

        if (tambahin) { // Jika tombol tambah diklik
            query(sqlAdd, true); // Jika query tambah maka benar
            // Lalu menampilkan dialog
            JOptionPane.showMessageDialog(this, "Sukses menambah data!", "Kependudukan App", JOptionPane.INFORMATION_MESSAGE & JOptionPane.OK_OPTION);
        } else {
            query(sqlEdit, true); // Jika query edit maka benar
            // Lalu menampilkan dialog
            JOptionPane.showMessageDialog(this, "Sukses mengubah data!", "Kependudukan App", JOptionPane.INFORMATION_MESSAGE & JOptionPane.OK_OPTION);
        }
        query("from Users", false);
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        //Semua Tampilan GUI From
    }//GEN-LAST:event_txtCariActionPerformed

    private void tableKependudukanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKependudukanMouseClicked
        // Table Kependudukan
        // Seluruh isi dari table yang ada di Jframe
        int row = tableKependudukan.getSelectedRow();
        txtID.setText(tableKependudukan.getModel().getValueAt(row, 0).toString());
        txtNama.setText(tableKependudukan.getModel().getValueAt(row, 1).toString());
        txtAlamat.setText(tableKependudukan.getModel().getValueAt(row, 2).toString());
        txtEmail.setText(tableKependudukan.getModel().getValueAt(row, 3).toString());
        txtPassword.setText(tableKependudukan.getModel().getValueAt(row, 4).toString());
    }//GEN-LAST:event_tableKependudukanMouseClicked

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // Field Cari
        // Membuat query untuk pencarian berdasrkan nama
        query("from Users s Where s.nama LIKE '%" + txtCari.getText() + "%'", false);
    }//GEN-LAST:event_txtCariKeyReleased

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // Tombol Exit
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    protected void query(String str, boolean update) { //membuat parameter
        try {
            // Mengambil sesi dari com.kependudukan.util dengan nama KependudukanHibernateUtil.java
            Session sesi = KependudukanHibernateUtil.getSessionFactory().openSession(); 
            sesi.beginTransaction();

            /**
             * Cek perintah untuk mengubah/menghapus/menambah data Jika iya
             */
            Query sql;
            if (update) {
                sql = sesi.createSQLQuery(str);
                sql.executeUpdate();
            } else {
                // Jika hanya menampilkan data
                sql = sesi.createQuery(str);
                List data = sql.list();
                display(data, update);
            }

            sesi.getTransaction().commit();
            sesi.close();
        } catch (HibernateException he) {
            JOptionPane.showMessageDialog(this, he.getMessage(), "Error", JOptionPane.ERROR_MESSAGE & JOptionPane.OK_OPTION);
        }
    }

    protected void display(List data, boolean update) {
        // Membuat title kolom untuk table
        Object[] kolom = new Object[5];
        kolom[0] = "ID";
        kolom[1] = "NAMA PENDUDUK";
        kolom[2] = "ALAMAT";
        kolom[3] = "EMAIL";
        kolom[4] = "PASSWORD";

        Object[][] baris = new Object[data.size()][5];
        int x = 0;
        while (x < data.size()) {
            /**
             * Users Dibuat dengan menggunakan Wizard Pojo lokasi
             * com.kependudukan.entity
             */
            Users user = (Users) data.get(x);
            // Membuat baris data table
            baris[x][0] = user.getId();
            baris[x][1] = user.getNama();
            baris[x][2] = user.getAlamat();
            baris[x][3] = user.getEmail();
            baris[x][4] = user.getPassword();

            x++;
        }
        tableKependudukan.setModel(new DefaultTableModel(baris, kolom));

        txtID.setText(tableKependudukan.getModel().getValueAt(0, 0).toString());
        txtNama.setText(tableKependudukan.getModel().getValueAt(0, 1).toString());
        txtAlamat.setText(tableKependudukan.getModel().getValueAt(0, 2).toString());
        txtEmail.setText(tableKependudukan.getModel().getValueAt(0, 3).toString());
        txtPassword.setText(tableKependudukan.getModel().getValueAt(0, 4).toString());

        cekFungsi(false);
    }

    protected void cekFungsi(boolean update) {
        /**
         * Kondisi apabila tombol tambah dan ubah di klik
         */
        if (update) {
            btnTambah.setEnabled(false); // Tombol mati
            btnUbah.setEnabled(false); // Tombol mati
            btnHapus.setEnabled(false); // Tombol mati
            btnBatal.setEnabled(true); // Tombol hidup
            btnSimpan.setEnabled(true); // Tombol hidup

            /**
             * Kondisi Input dan tombol
             */
            if (tambahin) {
                // Ketika Klik tombol Tambah
                // Maksud dari setText("") adalah untuk textfield agar kosong
                txtID.setText("");
                txtNama.setText("");
                txtAlamat.setText("");
                txtEmail.setText("");
                txtPassword.setText("");

                txtID.setEditable(false); // form mati
                txtNama.setEditable(true); // form hidup
                txtAlamat.setEditable(true); // form hidup
                txtEmail.setEditable(true); // form hidup
                txtPassword.setEditable(true); // form hidup
            } else {
                txtID.setEditable(false); // form mati
                txtNama.setEditable(true); // form hidup
                txtAlamat.setEditable(true); // form hidup
                txtEmail.setEditable(true); // form hidup
                txtPassword.setEditable(true); // form hidup
            }
        } else {
            btnTambah.setEnabled(true); // Tombol hidup
            btnUbah.setEnabled(true); // Tombol hidup
            btnHapus.setEnabled(true); // Tombol hidup
            btnBatal.setEnabled(false); // Tombol mati
            btnSimpan.setEnabled(false); // Tombol mati
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableKependudukan;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
